// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/figgerit/[figgerit].ts";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/api/timezone/[timezone].ts";
import * as $4 from "./routes/figgerits/[figgerit].tsx";
import * as $5 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Figgerit.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/figgerit/[figgerit].ts": $1,
    "./routes/api/joke.ts": $2,
    "./routes/api/timezone/[timezone].ts": $3,
    "./routes/figgerits/[figgerit].tsx": $4,
    "./routes/index.tsx": $5,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Figgerit.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
